language: cpp
compiler:
  - gcc
  - clang
env:
    # These are used by .travis-cmake.sh to set a configuration
    - STP_CONFIG=STATIC_LIB
    - STP_CONFIG=DYNAMIC_LIB
    - STP_CONFIG=DYNAMIC_AND_STATIC_LIB
    - STP_CONFIG=STATIC_BINARY
    - STP_CONFIG=RELEASE
before_install:
  - sudo apt-get install libboost-all-dev
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo pip install lit
# Initialise our submodules
  - git submodule init
  - git submodule update
  - mkdir build && cd build
  - mkdir simple_example
  - mkdir stp && cd stp
script:
# Build STP
  - ../../scripts/travis-cmake.sh ../../
  - make
  - make check
# Build example project. We assume that the build installed itself to the CMake
# user package registry (~/.cmake/packages/)
  - cd ../simple_example
  - cmake -G "Unix Makefiles" -DUSE_STP_SHARED_LIBRARY=$( test -f ../stp/lib/libstp.so && echo ON || echo OFF) ../../examples/simple
  - make
  - ./stp-example
