language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

dist: trusty
sudo: required

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "bCbWf/B++9y5YDn/ugMKVaV+ZmGCNNtxeWiPFfl7D/xwaj3yjy9yILMkqLcmNNc7rMQruEVx371rn+VURcLIFQtCJ+Uqj4vKdx7kSnhe2oNxKBMViAZU04nLSBB9ZNiH6TKvfqm4eUFprQd6AJ6T0GmB//lC1AgKSKNwSUJBMKc="
    - secure: "eYyuFa5eNIl/i/hInmCoVZv5pxPrFzLNPIQrMpWZNW6efDsQi/voxLUuTzD6L9HqnUgmLF+kVnGETYUTNMHHaWUqVT8Rhiu10UNBnEmIfZbe/SXKEJsvci0o0KrGgxtKDuCil7tdLF5IEcird/94zocPtCHdH4W8r/NzG0tFtDA="

  matrix:
    # These are used by .travis-cmake.sh to set a configuration
    - STP_CONFIG=NORM
    - STP_CONFIG=RELEASE
    - STP_CONFIG=NO_BOOST
    #- STP_CONFIG=KLEE
    - STP_CONFIG=COVERAGE
    - STP_CONFIG=STATIC_CMS
    - STP_CONFIG=INTREE_BUILD

matrix:
  include:
    # Covertiy scan should only run once
    - os: linux
      compiler: gcc
      env: COVERITY_SCAN=1 STP_CONFIG=NORM

  exclude:
    - os: linux
      compiler: clang
      env: STP_CONFIG=COVERAGE

  allow_failures:
    # Covertiy scan might fail
    - env: COVERITY_SCAN=1 STP_CONFIG=NORM

addons:
  coverity_scan:
    project:
      name: "stp/stp"
      description: "Simple Theorem Prover"
    notification_email: soos.mate@gmail.com
    build_command_prepend: "cmake .."
    build_command:   "make"
    branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y --force-yes cmake valgrind git zlib1g-dev

install:
#cmake
  - wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz
  - tar -xzf cmake-3.4.1.tar.gz
  - cd cmake-3.4.1/
  - ./configure
  - make
  - sudo make install
  - sudo update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
  - cmake --version
  - cd ..
# get and install minisat
  - mkdir minisat_git && cd minisat_git
  - git clone --depth 1 https://github.com/stp/minisat
  - cd minisat
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../..
#coveralls
  - sudo pip install cpp-coveralls
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
#
# get LIT from pip
  - sudo pip install lit
#
# Initialise our submodules
  - git submodule init
  - git submodule update
#
#set up build environment
  - mkdir -p build

script:
  - if [ "$COVERITY_SCAN" != "1" ]; then ./scripts/travis-cmake.sh ; fi

