language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-all-dev
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo pip install lit
# Initialise our submodules
  - git submodule init
  - git submodule update
  - mkdir build && cd build
  - mkdir simple_example
  - mkdir stp && cd stp
  - cmake -G "Unix Makefiles" -DENABLE_TESTING:BOOL=ON ../..
script:
# Build STP
  - make
  - make check
# Build example project. We assume that the build installed itself to the CMake user package registry (~/.cmake/packages/)
  - cd ../simple_example
  - cmake -G "Unix Makefiles" ../../examples/simple
  - make
